[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "torchsig"
description = "Signal Processing Machine Learning Toolkit"
authors = [
    {name = "TorchSig Team"},
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["signal processing", "machine learning"]
dependencies = [
    "torch==2.6.0",
    "torchvision==0.21.0",
    "tqdm==4.67.1",
    "opencv-python==4.11.0.86",
    "numpy==2.1.1",
    "scipy==1.15.2",
    "h5py==3.13.0",
    "matplotlib==3.10.1",
    "pywavelets==1.8.0",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "torchaudio==2.6.0",
    "timm==1.0.15",
    "pytorch-lightning==2.5.1",
    "ultralytics==8.3.94",
    "jupyter-bbox-widget==0.6.0",
    "torchinfo==1.8.0",
    "sigmf==1.2.6",
    "pytest==8.3.5",
    "zarr==2.18.3",
    "pylint==3.3.6",
    "pytest-cov==6.0.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.11.14",
    "aiosignal==1.3.2",
    "anywidget==0.9.16",
    "asciitree==0.3.3",
    "astroid==3.3.9",
    "asttokens==3.0.0",
    "async-timeout==5.0.1",
    "attrs==25.3.0",
    "build==1.2.2.post1",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "comm==0.2.2",
    "contourpy==1.3.1",
    "coverage==7.7.0",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "dill==0.3.9",
    "exceptiongroup==1.2.2",
    "executing==2.2.0",
    "fasteners==0.19",
    "filelock==3.18.0",
    "fonttools==4.56.0",
    "frozenlist==1.5.0",
    "fsspec==2025.3.0",
    "huggingface-hub==0.29.3",
    "idna==3.10",
    "iniconfig==2.1.0",
    "ipython==8.34.0",
    "ipywidgets==8.1.5",
    "isort==6.0.1",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "joblib==1.4.2",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jupyterlab-widgets==3.0.13",
    "kiwisolver==1.4.8",
    "lightning-utilities==0.14.2",
    "markupsafe==3.0.2",
    "matplotlib-inline==0.1.7",
    "mccabe==0.7.0",
    "mpmath==1.3.0",
    "multidict==6.2.0",
    "networkx==3.4.2",
    "numcodecs==0.13.1",
    "packaging==24.2",
    "parso==0.8.4",
    "pexpect==4.9.0",
    "pillow==11.1.0",
    "pip==25.0.1",
    "pip-tools==7.4.1",
    "platformdirs==4.3.7",
    "pluggy==1.5.0",
    "prompt-toolkit==3.0.50",
    "propcache==0.3.0",
    "psutil==7.0.0",
    "psygnal==0.12.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "py-cpuinfo==9.0.0",
    "pygments==2.19.1",
    "pyparsing==3.2.1",
    "pyproject-hooks==1.2.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.1",
    "pyyaml==6.0.2",
    "referencing==0.36.2",
    "requests==2.32.3",
    "rpds-py==0.23.1",
    "safetensors==0.5.3",
    "seaborn==0.13.2",
    "setuptools==77.0.3",
    "six==1.17.0",
    "stack-data==0.6.3",
    "sympy==1.13.1",
    "threadpoolctl==3.6.0",
    "tomli==2.2.1",
    "tomlkit==0.13.2",
    "torchmetrics==1.7.0",
    "traitlets==5.14.3",
    "typing-extensions==4.12.2",
    "tzdata==2025.1",
    "ultralytics-thop==2.0.14",
    "urllib3==2.3.0",
    "wcwidth==0.2.13",
    "wheel==0.45.1",
    "widgetsnbextension==4.0.13",
    "yarl==1.18.3",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "torchsig.__version__"}

[tool.setuptools.package-data]
"torchsig.datasets.default_configs" = ["*.yaml"]

[tool.coverage.run]
branch = true
source = ["torchsig"]

[tool.coverage.report]
show_missing = true
skip_covered = true
omit = [
    "torchsig/image_datasets/*",
    "torchsig/models/*"
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
addopts = "-m 'not slow' --cov=torchsig --cov-report=xml --cov-report=term --junitxml=report.xml"
testpaths = ["tests"]
